# Build configure for https://www.tea-ci.org (fork of Drone CI with Msys2 support)
build:
  image: teaci/msys64
  shell: mingw64
  pull: true
  branches:
    -master
  environment:
    - SUBTARGET=tiny
    - MINGW64=/c/msys64/mingw64
    - MAME=mametiny64.exe
  commands:
    - make && ./$$MAME -validate
  
