# Build configure for https://www.tea-ci.org (fork of Drone CI with Msys2 support)
build:
  image: teaci/msys64
  shell: mingw64
  pull: true
  branches:
    -master
  environment:
    - SUBTARGET=tiny
    - MINGW64=/c/msys64/mingw64
    - MAME_EXE=mametiny64.exe
  commands:
    - make
    - ./$MAME_EXE -validate
    - echo haha1
    - echo haha2
    - echo haha3
    - echo haha4
    - echo haha5
    - echo haha6
    - echo haha7
    - echo haha8
